imports:
  - { resource: config.env }

version: 2.1

jobs:
  build:
    environment:
      RENDER_DEPLOY_LINK: ${RENDER_DEPLOY_LINK}
    docker:
      - image: circleci/node

    steps:
      - checkout

      # Install TypeScript
      - run: sudo npm install -g typescript

      # Install project dependencies
      - run: npm install

      # Compile TypeScript source code
      - run: npm run build

      # Run tests
      - run: npm run test

      # Deploy on render
      - run: curl ${RENDER_DEPLOY_LINK}
