---
version: "3"
services:
  app:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - "./src:/index"
    working_dir: "/src"
    command: "npm start"
    depends_on:
      - tests
  tests:
    image: node:latest
    volumes:
      - "./app:/app"
    working_dir: "/src"
    command: "npm run test"
